apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "karma"
  name: "karma-config"
  namespace: monitoring
data:
  karma.conf: |
    alertmanager:
      interval: 60s
      servers:
      - name: gauss-alert-manager
        uri: http://alertmanager.monitoring.svc.cluster.local:9093
        timeout: 10s
        proxy: true
        readonly: false
        headers:
          X-Auth-Test: karma
    karma:
      name: karma-prod
    labels:
      color:
        static:
          - job
        unique:
          - cluster
          - instance
          - "@receiver"
      keep: []
      strip: []
    listen:
      address: "0.0.0.0"
      port: 8080
      prefix: /
    log:
      config: false
      level: info
    ui:
      refresh: 30s
      hideFiltersWhenIdle: true
      colorTitlebar: false
      minimalGroupWidth: 420
      alertsPerGroup: 5
      collapseGroups: collapsedOnMobile

