apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "karma"
  name: "karma-config"
  namespace: monitoring
data:
  karma.conf: |
    alertmanager:
      interval: 60s
      servers:
      - name: gauss-alert-manager
        uri: http://alertmanager.monitoring.svc.cluster.local:9093
        timeout: 10s
        proxy: true
        readonly: false
        headers:
          X-Auth-Test: karma
    annotations:
      default:
        hidden: true
      hidden: []
      visible: []
    filters:
      default:
        - "@state=active"
        - team=firecracker
        - alertname!~Inhibition
        - alertname!~Heartbeat
    grid:
      sorting:
        order: label
        reverse: false
        label: severity
        customValues:
          labels: {}
    karma:
      name: KarmaGauss
    labels:
      color:
        static:
          - cluster_id
          - alert_name
        custom:
          severity:
          - value: heartbeat
            color: "#87c4e0"
          - value: notify
            color: "#ffae42"
          - value: page
            color: "#ff220c"
        unique:
          - installation
          - team
          - customer
          - provider
          - pipeline
          - area
          - topic
          - cluster_type
          - namespace
          - "@receiver"
      keep: []
      strip: []
    listen:
      address: "0.0.0.0"
      port: 8080
      prefix: /
    log:
      config: false
      level: info
    ui:
      refresh: 30s
      hideFiltersWhenIdle: true
      colorTitlebar: false
      minimalGroupWidth: 420
      alertsPerGroup: 1
      collapseGroups: collapsed
      multiGridLabel: "severity"