apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "labels.common" . | nindent 8 }}
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
    spec:
      securityContext:
        runAsUser: 1000
      serviceAccountName: {{ include "resource.default.name" . }}
      containers:
        - name: {{ include "name" . }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          - name: CONFIG_FILE
            value: /etc/karma/karma.conf
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.delay }}
            periodSeconds: {{ .Values.readinessProbe.period }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: karma-config
              mountPath: /etc/karma
      volumes:
      - name: karma-config
        configMap:
          name: {{ .Values.name }}
