{{- if .Values.oauth2.enabled }}
{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{ else }}
apiVersion: networking.k8s.io/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: {{ include "resource.default.name" . }}-proxy
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: alertmanager-dashboard.giantswarm.io
    http:
      paths:
      - backend:
          serviceName: {{ .Values.oauth2.serviceName }}
          servicePort: {{ .Values.oauth2.port }}
        path: /oauth2
        pathType: ImplementationSpecific
  - host: alertmanager-dashboard.{{ .Values.baseDomain }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.oauth2.serviceName }}
          servicePort: {{ .Values.oauth2.port }}
        path: /oauth2
        pathType: ImplementationSpecific
  tls:
    - hosts:
        - alertmanager-dashboard.giantswarm.io
        - alertmanager-dashboard.{{ .Values.baseDomain }}
      secretName: karma-tls
{{- end }}

