apiVersion: v1
appVersion: "0.81"
description: A Helm chart for Karma - a UI for Prometheus Alertmanager
name: karma
home: https://github.com/giantswarm/karma-app
sources:
  - https://github.com/prymitive/karma
version: [[ .Version ]]
